import { describe,it,expect } from 'vitest'
import { readFile } from 'node:fs/promises'
import { PDFDocument } from 'pdf-lib'
import { emptyWorkspace,newInvoice,applyCommand,totals,status,nextMonth,runSchedules,issueErrors,today } from '../src/shared/domain'
import { renderPDF } from '../src/shared/pdf'
function fixture(){let w=emptyWorkspace();w.business.name='Test Studio';w.business.address='1 Example Road\nLondon';const i=newInvoice(w);i.client.name='Example Client';i.client.email='test@example.com';i.lines=[{id:crypto.randomUUID(),description:'Design services',quantity:'1',rate:'1250',unit:'fixed'}];w=applyCommand(w,{type:'draft',value:i});return {w,i}}
describe('Money and issuance',()=>{
 it('rounds fractional rates per line and applies discount before tax',()=>{const {i}=fixture();i.lines[0].quantity='3';i.lines[0].rate='0.105';i.tax='20';i.discount='10';i.discountType='percent';expect(totals(i)).toMatchObject({subtotal:'0.32',discount:'0.03',tax:'0.06',total:'0.35'})})
 it('respects zero- and three-decimal currencies',()=>{const {i}=fixture();i.currency='JPY';i.lines[0].rate='10.5';expect(totals(i).total).toBe('11');i.currency='KWD';expect(totals(i).total).toBe('10.500')})
 it('allocates unique numbers and snapshots business details',()=>{let {w,i}=fixture();w=applyCommand(w,{type:'issue',id:i.id});const first=w.invoices[0];expect(first.number).toMatch(/INV-\d{4}-0001/);w=applyCommand(w,{type:'business',value:{...w.business,name:'New name'}});expect(w.invoices[0].business?.name).toBe('Test Studio');const id=crypto.randomUUID();w=applyCommand(w,{type:'duplicate',id:i.id,newId:id});expect(w.invoices[0].number).toBe('');w=applyCommand(w,{type:'issue',id});expect(w.invoices[0].number).toMatch(/0002$/);expect(()=>applyCommand(w,{type:'draft',value:first})).toThrow('Issued invoices')})
 it('permits incomplete drafts but prevents incomplete issuance',()=>{const w=emptyWorkspace();const i=newInvoice(w);expect(()=>applyCommand(w,{type:'draft',value:i})).not.toThrow();expect(issueErrors(i,w.business).length).toBeGreaterThan(0)})
 it('rejects discount over 100 percent',()=>{const {i,w}=fixture();i.discountType='percent';i.discount='101';expect(issueErrors(i,w.business)).toContain('Discount exceeds the subtotal.')})
})
describe('Payments and lifecycle',()=>{
 it('tracks partial payment, overdue, paid and reversal without deleting history',()=>{let {w,i}=fixture();w=applyCommand(w,{type:'issue',id:i.id});const id=crypto.randomUUID();w=applyCommand(w,{type:'payment',id:i.id,value:{id,amount:'250',date:today(),method:'Bank',reference:'',notes:'',reversed:false}});expect(status(w.invoices[0],i.issueDate)).toBe('partially paid');expect(status(w.invoices[0],'2099-01-01')).toBe('overdue');expect(totals(w.invoices[0]).balance).toBe('1000.00');expect(()=>applyCommand(w,{type:'void',id:i.id,reason:'Cancelled'})).toThrow('Reverse');w=applyCommand(w,{type:'reverse',id:i.id,paymentId:id});expect(w.invoices[0].payments).toHaveLength(1);expect(totals(w.invoices[0]).balance).toBe('1250.00')})
 it('rejects overpayment and duplicate payments',()=>{let {w,i}=fixture();w=applyCommand(w,{type:'issue',id:i.id});const value={id:crypto.randomUUID(),amount:'1251',date:today(),method:'Bank',reference:'',notes:'',reversed:false};expect(()=>applyCommand(w,{type:'payment',id:i.id,value})).toThrow();value.amount='1250';w=applyCommand(w,{type:'payment',id:i.id,value});expect(status(w.invoices[0])).toBe('paid');expect(()=>applyCommand(w,{type:'payment',id:i.id,value})).toThrow('already recorded')})
 it('voiding revokes sharing and disables reminders',()=>{let {w,i}=fixture();w=applyCommand(w,{type:'issue',id:i.id});w=applyCommand(w,{type:'share',id:i.id,expires:'2099-01-01'});w=applyCommand(w,{type:'void',id:i.id,reason:'Cancelled'});expect(w.invoices[0].share).toBeUndefined();expect(w.invoices[0].number).not.toBe('')})
})
describe('Schedules',()=>{
 it('keeps the original month-end anchor',()=>{expect(nextMonth('2026-01-31',1,31)).toBe('2026-02-28');expect(nextMonth('2026-02-28',1,31)).toBe('2026-03-31')})
 it('creates one draft per occurrence despite duplicate scheduled runs',()=>{let {w,i}=fixture();w=applyCommand(w,{type:'schedule',value:{id:crypto.randomUUID(),invoiceId:i.id,nextDate:'2026-09-12',months:1,day:12,paused:false}});const now=new Date('2026-09-12T10:00:00Z');w=runSchedules(w,now);expect(w.invoices).toHaveLength(2);w=runSchedules(w,now);expect(w.invoices).toHaveLength(2);expect(w.schedules[0].nextDate).toBe('2026-10-12')})
})
describe('PDF documents',()=>{
 it('renders Unicode and long descriptions across readable pages',async()=>{const {i,w}=fixture();i.client.name='Zoë Müller';i.breakdown='Résumé – café\n'.repeat(200);i.lines=Array.from({length:45},(_,n)=>({...i.lines[0],id:crypto.randomUUID(),description:`Service ${n}: `+'Detailed work description '.repeat(12)}));const font=new Uint8Array(await readFile('public/fonts/NotoSans-Regular.ttf'));const bytes=await renderPDF(i,w.business,font);const pdf=await PDFDocument.load(bytes);expect(pdf.getPageCount()).toBeGreaterThan(2);const breakdown=await PDFDocument.load(await renderPDF(i,w.business,font,true));expect(breakdown.getPageCount()).toBeGreaterThan(2)},20000)
})
