import { Hono } from 'hono'
import { bodyLimit } from 'hono/body-limit'
import { secureHeaders } from 'hono/secure-headers'
import { z } from 'zod'
import { neon } from '@neondatabase/serverless'
import { Resend } from 'resend'
import { zipSync, strToU8 } from 'fflate'
import { auth } from './auth'
import { read, write, update, Conflict } from './store'
import { applyCommand, buildClientPortalView, buildClientStatement, commandSchema, today, type Workspace } from '../shared/domain'
import { document, statementDocument } from './documents'
import { filename, filenameStatement } from '../shared/pdf'
import { deliver, scheduled } from './delivery'

const app=new Hono<{Bindings:Env;Variables:{owner:string}}>()
app.use('*',secureHeaders())
app.use('/api/*',bodyLimit({maxSize:6_000_000,onError:c=>c.json({error:'Request is too large'},413)}))
app.use('/api/*',async(c,next)=>{c.header('Cache-Control','no-store');c.header('Referrer-Policy','no-referrer');c.header('X-Robots-Tag','noindex, nofollow');if(!['GET','HEAD','OPTIONS'].includes(c.req.method)&&!c.req.path.startsWith('/api/webhooks/')&&!c.req.path.startsWith('/api/public/portal/')){if(c.req.header('Origin')!==c.env.APP_URL)return c.json({error:'Untrusted request origin'},403)}await next()})
const configured=(env:Env)=>!!(env.DATABASE_URL&&env.BETTER_AUTH_SECRET)
app.get('/api/health',c=>c.json({ok:true}))
app.get('/api/config',c=>c.json({configured:configured(c.env),emailEnabled:!!c.env.RESEND_API_KEY}))
app.on(['GET','POST'],'/api/auth/*',async c=>{if(!configured(c.env))return c.json({error:'Authentication needs database and session configuration'},503);if(c.req.path.endsWith('/sign-in/magic-link')){if(!c.env.RESEND_API_KEY)return c.json({error:'Sign-in email is not configured yet'},503);const body=await c.req.raw.clone().json() as {email?:string};if(body.email?.toLowerCase()!==c.env.OWNER_EMAIL.toLowerCase())return c.json({status:true})}return auth(c.env).handler(c.req.raw)})
app.post('/api/webhooks/resend',async c=>{if(!c.env.RESEND_WEBHOOK_SECRET)return c.json({error:'Webhook unavailable'},503);let event;try{event=new Resend(c.env.RESEND_API_KEY).webhooks.verify({payload:await c.req.text(),headers:{id:c.req.header('svix-id')??'',timestamp:c.req.header('svix-timestamp')??'',signature:c.req.header('svix-signature')??''},webhookSecret:c.env.RESEND_WEBHOOK_SECRET})}catch{return c.json({error:'Invalid signature'},400)}const sql=neon(c.env.DATABASE_URL);const data=event.data as unknown as Record<string,unknown>|undefined;if(!data)return c.json({ok:true});const emailId=(data.email_id??data.id) as string|undefined;if(!emailId)return c.json({ok:true});const rows=await sql`SELECT owner_id FROM invoice_workspaces WHERE data->'messages' @> ${JSON.stringify([{providerId:emailId}])}::jsonb`;for(const row of rows)await update(c.env,row.owner_id,w=>{for(const m of w.messages.filter(m=>m.providerId===emailId)){if(['email.bounced','email.complained'].includes(event.type))m.status='bounced';else if(event.type==='email.delivered'&&m.status!=='bounced')m.status='delivered';else if(event.type==='email.sent'&&['queued','sending'].includes(m.status))m.status='sent'}return w});return c.json({ok:true})})
app.get('/api/public/:owner/:token/:kind',async c=>{if(!configured(c.env))return c.json({error:'Unavailable'},503);const sql=neon(c.env.DATABASE_URL);const [row]=await sql`SELECT data FROM invoice_workspaces WHERE owner_id=${c.req.param('owner')}`;if(!row)return c.json({error:'Link unavailable'},404);const w=row.data as Workspace;const invoice=w.invoices.find(i=>i.share&&i.share.token===c.req.param('token')&&i.share.expires>=today(w.business.timezone)&&i.lifecycle==='issued');if(!invoice)return c.json({error:'Link expired or revoked'},404);const kind=c.req.param('kind');const breakdown=kind==='breakdown';const download=kind==='download'||c.req.query('download')==='true';const bytes=await document(c.env,c.req.param('owner'),w,invoice,breakdown);return new Response(new Uint8Array(bytes),{headers:{'Content-Type':'application/pdf','Content-Disposition':`${download?'attachment':'inline'}; filename*=UTF-8''${encodeURIComponent(filename(invoice,breakdown))}`,'Cache-Control':'no-store, no-cache, must-revalidate, max-age=0','Pragma':'no-cache','X-Robots-Tag':'noindex, nofollow, noarchive','Referrer-Policy':'no-referrer'}})})
app.get('/api/public/portal/:owner/:token',async c=>{if(!configured(c.env))return c.json({error:'Unavailable'},503);const sql=neon(c.env.DATABASE_URL);const [row]=await sql`SELECT data FROM invoice_workspaces WHERE owner_id=${c.req.param('owner')}`;if(!row)return c.json({error:'Portal unavailable'},404);const w=row.data as Workspace;try{const portal=buildClientPortalView(w,c.req.param('token'));return c.json(portal)}catch(e){return c.json({error:e instanceof Error?e.message:'Portal unavailable'},404)}})
app.get('/api/public/portal/:owner/:token/invoices/:id/pdf',async c=>{if(!configured(c.env))return c.json({error:'Unavailable'},503);const sql=neon(c.env.DATABASE_URL);const [row]=await sql`SELECT data FROM invoice_workspaces WHERE owner_id=${c.req.param('owner')}`;if(!row)return c.json({error:'Portal unavailable'},404);const w=row.data as Workspace;const client=(w.clients||[]).find(c1=>c1.portal&&c1.portal.token===c.req.param('token'));if(!client||!client.portal||client.portal.expires<today(w.business.timezone)){return c.json({error:'Portal expired or revoked'},404)}if(client.portal.allowedInvoiceIds&&client.portal.allowedInvoiceIds.length>0){if(!client.portal.allowedInvoiceIds.includes(c.req.param('id'))){return c.json({error:'Invoice not authorized for this portal'},403)}}const invoice=(w.invoices||[]).find(i=>i.id===c.req.param('id')&&i.clientId===client.id&&i.lifecycle==='issued');if(!invoice)return c.json({error:'Invoice not found'},404);const breakdown=c.req.query('breakdown')==='true';const download=c.req.query('download')==='true';const bytes=await document(c.env,c.req.param('owner'),w,invoice,breakdown);return new Response(new Uint8Array(bytes),{headers:{'Content-Type':'application/pdf','Content-Disposition':`${download?'attachment':'inline'}; filename*=UTF-8''${encodeURIComponent(filename(invoice,breakdown))}`,'Cache-Control':'no-store, no-cache, must-revalidate, max-age=0','Pragma':'no-cache','X-Robots-Tag':'noindex, nofollow, noarchive','Referrer-Policy':'no-referrer'}})})
app.get('/api/public/portal/:owner/:token/statement/pdf',async c=>{if(!configured(c.env))return c.json({error:'Unavailable'},503);const sql=neon(c.env.DATABASE_URL);const [row]=await sql`SELECT data FROM invoice_workspaces WHERE owner_id=${c.req.param('owner')}`;if(!row)return c.json({error:'Portal unavailable'},404);const w=row.data as Workspace;const client=(w.clients||[]).find(c1=>c1.portal&&c1.portal.token===c.req.param('token'));if(!client||!client.portal||client.portal.expires<today(w.business.timezone)){return c.json({error:'Portal expired or revoked'},404)}if(client.portal.allowStatements===false){return c.json({error:'Statements are not enabled for this portal'},403)}const day=today(w.business.timezone);const start=c.req.query('start')||`${day.slice(0,4)}-01-01`;const end=c.req.query('end')||day;const currency=client.currency||w.business.currency;const stmt=buildClientStatement(w,client.id,currency,start,end);const bytes=await statementDocument(c.env,c.req.param('owner'),w,stmt);return new Response(new Uint8Array(bytes),{headers:{'Content-Type':'application/pdf','Content-Disposition':`inline; filename*=UTF-8''${encodeURIComponent(filenameStatement(stmt))}`,'Cache-Control':'no-store, no-cache, must-revalidate, max-age=0','Pragma':'no-cache','X-Robots-Tag':'noindex, nofollow, noarchive','Referrer-Policy':'no-referrer'}})})
app.post('/api/public/portal/:owner/:token/notice',async c=>{if(!configured(c.env))return c.json({error:'Unavailable'},503);const body=await c.req.json() as {date?:string;amount?:string;reference?:string;notes?:string};if(!body.date)return c.json({error:'Payment date is required'},400);const token=c.req.param('token');const owner=c.req.param('owner');const current=await read(c.env,owner);const client=(current.data.clients||[]).find(c1=>c1.portal&&c1.portal.token===token);if(!client)return c.json({error:'Portal link not found or revoked'},404);await update(c.env,owner,w=>{return applyCommand(w,{type:'recordClientPaymentNotice',clientId:client.id,token,notice:{id:crypto.randomUUID(),date:body.date!,amount:body.amount,reference:body.reference,notes:body.notes}})});return c.json({ok:true})})
app.use('/api/private/*',async(c,next)=>{if(!configured(c.env))return c.json({error:'Database and authentication are not configured'},503);const session=await auth(c.env).api.getSession({headers:c.req.raw.headers});if(!session||!session.user.emailVerified||session.user.email.toLowerCase()!==c.env.OWNER_EMAIL.toLowerCase())return c.json({error:'Sign in to continue'},401);c.set('owner',session.user.id);await next()})
app.get('/api/private/workspace',async c=>c.json({...await read(c.env,c.get('owner')),owner:c.get('owner')}))
app.post('/api/private/command',async c=>{const body=z.object({version:z.number().int().min(0),command:commandSchema}).parse(await c.req.json());const current=await read(c.env,c.get('owner'));if(current.version!==body.version)throw new Conflict('Newer changes exist. Reload or recover your draft.');if(body.command.type==='business'&&body.command.value.logo){if(!/^data:image\/(png|jpeg);base64,[A-Za-z0-9+/=]+$/.test(body.command.value.logo))return c.json({error:'Use a PNG or JPEG logo'},400);if(c.env.DOCUMENTS){const mime=body.command.value.logo.startsWith('data:image/png')?'image/png':'image/jpeg';const ext=mime==='image/png'?'png':'jpg';const rawData=body.command.value.logo.split(',')[1];const bytes=Uint8Array.from(atob(rawData),x=>x.charCodeAt(0));c.executionCtx?.waitUntil?.(c.env.DOCUMENTS.put(`${c.get('owner')}/logo.${ext}`,bytes,{httpMetadata:{contentType:mime}}))}}if(body.command.type==='send'&&!c.env.RESEND_API_KEY)return c.json({error:'Email sending is not configured. Your draft is saved.'},503);const data=applyCommand(current.data,body.command);const saved=await write(c.env,c.get('owner'),current.version,data);if(body.command.type==='send'){const id=body.command.id;c.executionCtx.waitUntil(deliver(c.env,c.get('owner'),id))}return c.json(saved)})
app.get('/api/private/logo',async c=>{if(!c.env.DOCUMENTS)return c.json({error:'Document storage not configured'},503);const png=await c.env.DOCUMENTS.get(`${c.get('owner')}/logo.png`);if(png)return new Response(await png.arrayBuffer(),{headers:{'Content-Type':'image/png','Cache-Control':'private, max-age=3600'}});const jpg=await c.env.DOCUMENTS.get(`${c.get('owner')}/logo.jpg`);if(jpg)return new Response(await jpg.arrayBuffer(),{headers:{'Content-Type':'image/jpeg','Cache-Control':'private, max-age=3600'}});return c.json({error:'No logo uploaded'},404)})
app.get('/api/private/invoices/:id/pdf',async c=>{const w=await read(c.env,c.get('owner'));const i=w.data.invoices.find(i=>i.id===c.req.param('id'));if(!i)return c.json({error:'Invoice not found'},404);const breakdown=c.req.query('breakdown')==='true';const bytes=await document(c.env,c.get('owner'),w.data,i,breakdown);return new Response(new Uint8Array(bytes),{headers:{'Content-Type':'application/pdf','Content-Disposition':`attachment; filename*=UTF-8''${encodeURIComponent(filename(i,breakdown))}`,'Cache-Control':'no-store'}})})
app.get('/api/private/export',async c=>{const w=await read(c.env,c.get('owner'));if(c.req.query('format')!=='zip')return c.json({format:'invoiceui-backup',schemaVersion:1,exportedAt:new Date().toISOString(),...w});const files:Record<string,Uint8Array>={'workspace.json':strToU8(JSON.stringify({format:'invoiceui-backup',schemaVersion:1,...w},null,2))};let size=files['workspace.json'].length;for(const i of w.data.invoices.filter(i=>i.issuedAt)){for(const breakdown of i.breakdown?[false,true]:[false]){const bytes=await document(c.env,c.get('owner'),w.data,i,breakdown);size+=bytes.length;if(size>40_000_000)return c.json({error:'PDF archive exceeds 40MB; export JSON and download PDFs individually'},413);files[`${i.id}/${filename(i,breakdown)}`]=bytes}}return new Response(zipSync(files),{headers:{'Content-Type':'application/zip','Content-Disposition':'attachment; filename="InvoiceUI-backup.zip"','Cache-Control':'no-store'}})})
app.notFound(c=>c.json({error:'Route not found'},404))
app.onError((error,c)=>{if(error instanceof Conflict)return c.json({error:error.message},409);if(error instanceof z.ZodError)return c.json({error:error.issues.map(i=>`${i.path.join('.')}: ${i.message}`).join('; ')},400);console.error(JSON.stringify({event:'api_error',path:c.req.path,name:error.name}));return c.json({error:error.message.startsWith('This')?error.message:'The request could not be completed. Check the data or try again.'},400)})
export { app }
export default {fetch:app.fetch,scheduled:async(_event:ScheduledController,env:Env)=>{await scheduled(env)}} satisfies ExportedHandler<Env>
