import { useCallback,useEffect,useRef,useState } from 'react'
import { applyCommand,emptyWorkspace,type Command,type Envelope } from '../shared/domain'
const DEMO_KEY='invoiceui:demo:v1'
export class ApiError extends Error {constructor(message:string,public status:number){super(message)}}
export async function api<T>(url:string,init?:RequestInit):Promise<T>{const response=await fetch(url,{credentials:'same-origin',...init,headers:{'Content-Type':'application/json',...init?.headers}});const body=await response.json();if(!response.ok)throw new ApiError(body.error||body.message||'Request failed',response.status);return body}
export function useWorkspace(){const [envelope,setEnvelope]=useState<Envelope|null>(null);const [owner,setOwner]=useState('');const [demo,setDemo]=useState(false);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [config,setConfig]=useState({configured:false,emailEnabled:false});const current=useRef<Envelope|null>(null);const queue=useRef<Promise<unknown>>(Promise.resolve());const isDemoRef=useRef(false);const update=(e:Envelope)=>{current.current=e;setEnvelope(e)};
 const reload=useCallback(async()=>{setError('');try{const c=await api<typeof config>('/api/config');setConfig(c);if(c.configured){try{const result=await api<Envelope&{owner:string}>('/api/private/workspace');setOwner(result.owner);setDemo(false);isDemoRef.current=false;localStorage.removeItem('invoiceui:is_demo');update(result);return}catch(e){if(e instanceof ApiError&&e.status===401&&import.meta.env.DEV&&localStorage.getItem('invoiceui:is_demo')==='true'){const raw=localStorage.getItem(DEMO_KEY);const envData=raw?JSON.parse(raw) as Envelope:{version:0,data:emptyWorkspace()};envData.data.starters=envData.data.starters||[];update(envData);setOwner('demo');setDemo(true);isDemoRef.current=true;return}throw e}}}catch(e){if(!(e instanceof ApiError&&e.status===401))setError(e instanceof Error?e.message:'Could not connect')}finally{setLoading(false)}},[]);
 useEffect(()=>{void reload()},[reload]);
 const startDemo=()=>{if(!import.meta.env.DEV)return;try{const raw=localStorage.getItem(DEMO_KEY);const e=raw?JSON.parse(raw) as Envelope:{version:0,data:emptyWorkspace()};e.data.starters=e.data.starters||[];update(e);setOwner('demo');setDemo(true);isDemoRef.current=true;localStorage.setItem('invoiceui:is_demo','true');setError('')}catch{setError('Browser storage is unavailable or the local preview is invalid')}};
 const command=useCallback((command:Command):Promise<Envelope>=>{const task=queue.current.catch(()=>{}).then(async()=>{const e=current.current;if(!e)throw new Error('Workspace not loaded');let next:Envelope;const isLocalDemo=demo||isDemoRef.current||owner==='demo'||(import.meta.env.DEV&&localStorage.getItem('invoiceui:is_demo')==='true');if(isLocalDemo){const latest=JSON.parse(localStorage.getItem(DEMO_KEY)||JSON.stringify(e)) as Envelope;if(latest.version!==e.version)throw new ApiError('This local workspace changed in another tab. Reload before saving.',409);next={version:e.version+1,data:applyCommand(e.data,command)};localStorage.setItem(DEMO_KEY,JSON.stringify(next))}else next=await api<Envelope>('/api/private/command',{method:'POST',body:JSON.stringify({version:e.version,command})});update(next);return next});queue.current=task;return task},[demo,owner]);
 const refresh=async()=>{const isLocalDemo=demo||isDemoRef.current||owner==='demo'||(import.meta.env.DEV&&localStorage.getItem('invoiceui:is_demo')==='true');if(isLocalDemo){const raw=localStorage.getItem(DEMO_KEY);if(raw)update(JSON.parse(raw))}else await reload()};
 const logout=async()=>{await queue.current.catch(()=>{});const isLocalDemo=demo||isDemoRef.current||owner==='demo'||(import.meta.env.DEV&&localStorage.getItem('invoiceui:is_demo')==='true');if(!isLocalDemo)await api('/api/auth/sign-out',{method:'POST',body:'{}'});for(const key of Object.keys(localStorage))if(key.startsWith(`invoiceui:recovery:${owner}:`))localStorage.removeItem(key);localStorage.removeItem('invoiceui:is_demo');isDemoRef.current=false;current.current=null;setEnvelope(null);setOwner('');setDemo(false)};
 return {envelope,owner,demo,loading,error,config,command,refresh,logout,startDemo}
}
export function downloadBlob(blob:Blob,name:string){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.rel='noopener';document.body.appendChild(a);a.click();document.body.removeChild(a);setTimeout(()=>URL.revokeObjectURL(url),40000)}
